### ISSUE TITLE
Notice undefined index

### ISSUE THREAD

**Issue by Axel29** [mageplaza/magento-2-german-language-pack#1]
Hello,

When I install your language pack, I get the following notice breaking the website: 
Undefined offset: 1 in magento/framework/App/Language/Dictionary.php on line 196

When dumping the value with this code:
```php
if (empty($row[0])) {
    \Zend_Debug::dump($row, '$row');
    die;
}
```

I get the following result: 

```php
array(1) {
  [0] =>
  NULL
}
```

I looked for an empty key but couldn't find it.

**Comment by Axel29** [comment]
Hello again,

I debugged a bit more by dumping the file used, and it's not in the "de_DE.csv" file that there's an error but in the "github_contribution.csv" which has only two empty lines that breaks it.

In order to fix it, I had to remove these empty lines to make the project work again.

Could you please fix it? 

Thank you.

**Comment by imsamthomas** [comment]
Thanks for your report.
We are working on this now.

**Comment by Axel29** [comment]
Hi @imsamthomas,

Thank you for your quick action. It works again.

Have a good day.
