### ISSUE TITLE
Package won't install when it's a dependency of another package

### ISSUE THREAD

**Issue by pascaladriaansen** [mageplaza/magento-2-german-language-pack#2]
Hi,

I have created my own language pack that depends on this language pack. In the `composer.json` of my own language pack, I require `mageplaza/magento-2-french-language-pack` with:
```
"require": {
    "mageplaza/magento-2-german-language-pack": "dev-master"
  },
```

However, I'm getting the following error message when trying to install/update our language pack with Composer:
```
vendorname/language-de_de 1.0.2 requires mageplaza/magento-2-french-language-pack dev-master -> satisfiable by mageplaza/magento-2-french-language-pack[dev-master] but these conflict with your requirements or minimum-stability.
```
I don't want to change Magento's default `minimum-stability`, so currently the only way to install my own language pack is to also directly require yours in my `composer.json`.  

Would it be possible to start tagging versions so we can require the `mageplaza/magento-2-french-language-pack` package via a version constraint in stead of `dev-master`, thus requiring a _stable_ version of the package?

This is the case for all mageplaza language packs.

**Comment by imsamthomas** [comment]
Hi  @pascaladriaansen ,


I have added [lines](https://github.com/mageplaza/magento-2-german-language-pack/blob/master/composer.json#L10) which solve the problem, please check.
