### ISSUE TITLE
Empty de_DE.csv

### ISSUE THREAD

**Issue by SpaceCafe** [mageplaza/magento-2-german-language-pack#9]
Maybe it is helpful to not push an empty translation table.
Could you please revert it?

**Comment by josefbehr** [comment]
I concur wholeheartedly!

**Comment by torhoehn** [comment]
Would be great to have translations again. 🙄

**Comment by MyoDaisy** [comment]
Thanks for your report and sorry for any inconvenience.
We have fixed this issue. Please update the latest version or rollback to previous.

Magento removed a server related to Crowdin.
We have build a new server to resolve the problem.

To help Magento community, feel free to translate this language pack in Crowdin.
